console_title_template = '{{ .Folder }}'
version = 3
final_space = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ if .WSL }}WSL at{{ end }} {{.Icon}} '
    foreground = '#ffffff'
    background = '#3A3A3A'
    type = 'os'
    style = 'powerline'

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#3465a4'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      style = 'agnoster_short'
      max_depth = 2
      truncate_to_unique = true
      hide_root_location = true

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#282828'
    powerline_symbol = ''
    background = '#4e9a06'
    type = 'git'
    style = 'powerline'
    background_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}#c4a000{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}',
      '{{ if gt .Ahead 0 }}#B388FF{{ end }}',
      '{{ if gt .Behind 0 }}#B388FF{{ end }}'
    ]

    [blocks.segments.properties]
      github_icon = ' '
      branch_icon = ' '
      branch_identical_icon = '●'
      branch_template = '{{ trunc 25 .Branch }}'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#00acd7'
    type = 'go'
    style = 'powerline'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#4063D8'
    type = 'julia'
    style = 'powerline'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }} {{ if .Venv }}({{ .Venv }}){{ end }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#4B8BBE'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_virtual_env = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#AE1401'
    type = 'ruby'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    type = "node"
    style = "powerline"
    powerline_symbol = ""
    foreground = '#111111'
    background = "#6CA35E"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "lua"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#111111"
    background = "blue"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    template = '  '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#ffff66'
    type = 'root'
    style = 'powerline'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    foreground = 'black'
    background = 'red'
    powerline_symbol = ''
    template = ' {{ .FormattedMs }} '

    [blocks.segments.properties]
      threshold = 5000

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#FEAC19'
    type = 'azfunc'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false

  [[blocks.segments]]
    template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    type = 'aws'
    style = 'powerline'
    background_templates = ['{{if contains "default" .Profile}}#FFA400{{end}}', '{{if contains "jan" .Profile}}#f1184c{{end}}']

    [blocks.segments.properties]
      display_default = false

  [[blocks.segments]]
    type = "gcp"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#47888d"
    template = " 󱇶 {{.Project}} :: {{.Account}} "

  [[blocks.segments]]
    type = "docker"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#000000"
    background = "#0B59E7"
    template = "  {{ .Context }} "

    [blocks.segments.properties]
      display_mode = 'files'

  [[blocks.segments]]
    type = "kubectl"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#000000"
    background = "#ebcc34"
    template = "  {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} "

  [[blocks.segments]]
    background = "#a7cae1"
    foreground = "#100e23"
    powerline_symbol = ""
    template = "  {{ .Version }}"
    style = "powerline"
    type = "helm"

    [blocks.segments.properties]
      display_mode = 'files'

  [[blocks.segments]]
    type = "argocd"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#FFA400"
    template = "  {{ .Name }}:{{ .User }}@{{ .Server }} "

  [[blocks.segments]]
    type = "terraform"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#000000"
    background = "#ebcc34"
    template = "  {{.WorkspaceName}}"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}green{{end}}",
    ]
    background = 'transparent'
    template = '❯'

# [transient_prompt]
#   foreground_templates = [
#     "{{if gt .Code 0}}red{{end}}",
#     "{{if eq .Code 0}}green{{end}}",
#   ]
#   background = 'transparent'
#   template = '❯ '

[secondary_prompt]
  foreground = 'green'
  background = 'transparent'
  template = '❯❯ '
