console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .UserName }} '
    foreground = '#ffffff'
    background = '#c386f1'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    template = '   {{ .Path }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#ff479c'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      folder_separator_icon = '  '
      home_icon = '~'
      style = 'folder'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#193549'
    powerline_symbol = ''
    background = '#fffb38'
    type = 'git'
    style = 'powerline'
    background_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}',
      '{{ if gt .Ahead 0 }}#B388FF{{ end }}',
      '{{ if gt .Behind 0 }}#B388FF{{ end }}',
    ]

    [blocks.segments.properties]
      branch_template = '{{ trunc 25 .Branch }}'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#6CA35E'
    type = 'node'
    style = 'powerline'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#8ED1F7'
    type = 'go'
    style = 'powerline'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#4063D8'
    type = 'julia'
    style = 'powerline'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#FFDE57'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_virtual_env = false

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#AE1401'
    type = 'ruby'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#FEAC19'
    type = 'azfunc'
    style = 'powerline'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false

  [[blocks.segments]]
    template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    type = 'aws'
    style = 'powerline'
    background_templates = [
      '{{if contains "default" .Profile}}#FFA400{{end}}',
      '{{if contains "jan" .Profile}}#f1184c{{end}}',
    ]

    [blocks.segments.properties]
      display_default = false

  [[blocks.segments]]
    template = '  '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#ffff66'
    type = 'root'
    style = 'powerline'

  [[blocks.segments]]
    template = '<transparent></>  {{ .FormattedMs }}⠀'
    foreground = '#ffffff'
    background = '#83769c'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    trailing_diamond = ''
    template = '<parentBackground></>  '
    foreground = '#ffffff'
    background = '#00897b'
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}#e91e63{{ end }}']

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    template = '<#0077c2,transparent></>  {{ .Name }} <transparent,#0077c2></>'
    foreground = '#ffffff'
    background = '#0077c2'
    type = 'shell'
    style = 'plain'

  [[blocks.segments]]
    template = '  {{ .Icon }}{{ if ne .Status "stopped" }}{{ .Artist }} - {{ .Track }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#1BD760'
    type = 'ytm'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      paused_icon = ' '
      playing_icon = ' '

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#f36943'
    type = 'battery'
    style = 'powerline'
    background_templates = [
      '{{if eq "Charging" .State.String}}#40c4ff{{end}}',
      '{{if eq "Discharging" .State.String}}#ff5722{{end}}',
      '{{if eq "Full" .State.String}}#4caf50{{end}}',
    ]
    invert_powerline = true

    [blocks.segments.properties]
      charged_icon = ' '
      charging_icon = ' '
      discharging_icon = ' '

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .CurrentDate | date .Format }} '
    foreground = '#111111'
    background = '#2e9599'
    type = 'time'
    style = 'diamond'
    invert_powerline = true
