console_title_template = '{{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'green'
  background = 'transparent'

  # [transient_prompt]
  # template = '❯ '
  # background = 'transparent'
  # foreground_templates = [
  #   '{{if gt .Code 0}}red{{end}}',
  #   '{{if eq .Code 0}}green{{end}}',
  # ]

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ if .WSL }}WSL at{{ end }} {{.Icon}} '
    foreground = '#ffffff'
    background = '#3A3A3A'
    type = 'os'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#3465a4'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      hide_root_location = true
      max_depth = 2
      style = 'agnoster_short'
      truncate_to_unique = true

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }} {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#282828'
    powerline_symbol = ''
    background = '#4e9a06'
    type = 'git'
    style = 'powerline'
    background_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}#c4a000{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}',
      '{{ if gt .Ahead 0 }}#B388FF{{ end }}',
      '{{ if gt .Behind 0 }}#B388FF{{ end }}',
    ]

    [blocks.segments.properties]
      branch_icon = ' '
      branch_template = '{{ trunc 25 .Branch }}'
      cache_duration = 'none'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#00acd7'
    type = 'go'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#4063D8'
    type = 'julia'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#306998'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'
      fetch_virtual_env = true

  [[blocks.segments]]
    template = ' {{ if .Venv }}{{ .Venv }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#FFD43B'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'
      fetch_virtual_env = true

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#AE1401'
    type = 'ruby'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'
      fetch_version = true

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#6CA35E'
    type = 'node'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = '#111111'
    powerline_symbol = ''
    background = 'blue'
    type = 'lua'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  '
    foreground = '#111111'
    powerline_symbol = ''
    background = '#ffff66'
    type = 'root'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .FormattedMs }} '
    foreground = 'black'
    powerline_symbol = ''
    background = 'red'
    type = 'executiontime'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

  [[blocks.segments]]
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#FEAC19'
    type = 'azfunc'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'
      fetch_version = false

  [[blocks.segments]]
    template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    type = 'aws'
    style = 'powerline'
    background_templates = [
      '{{if contains "default" .Profile}}#FFA400{{end}}',
      '{{if contains "jan" .Profile}}#f1184c{{end}}',
    ]

    [blocks.segments.properties]
      cache_duration = 'none'
      display_default = false

  [[blocks.segments]]
    template = ' 󱇶 {{.Project}} :: {{.Account}} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#47888d'
    type = 'gcp'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Context }} '
    foreground = '#000000'
    powerline_symbol = ''
    background = '#0B59E7'
    type = 'docker'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'

  [[blocks.segments]]
    template = '  {{.Context}}{{if .Namespace}}::{{.Namespace}}{{end}} '
    foreground = '#000000'
    powerline_symbol = ''
    background = '#326CE5'
    type = 'kubectl'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .Version }}'
    foreground = '#100e23'
    powerline_symbol = ''
    background = '#a7cae1'
    type = 'helm'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'files'

  [[blocks.segments]]
    template = '  {{ .Name }}:{{ .User }}@{{ .Server }} '
    foreground = '#ffffff'
    powerline_symbol = ''
    background = '#FFA400'
    type = 'argocd'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{.WorkspaceName}}'
    foreground = '#000000'
    powerline_symbol = ''
    background = '#4040B2'
    type = 'terraform'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{if gt .Code 0}}red{{end}}',
      '{{if eq .Code 0}}green{{end}}',
    ]

    [blocks.segments.properties]
      cache_duration = 'none'
